export type Status = 'Implemented'|'Partially Implemented'|'Not Implemented'|'Not Applicable';
export const frameworks=['SOC 2','HIPAA','PCI DSS','NIST RMF','NIST 800-53'];
export const controls = Array.from({length:55}).map((_,i)=>({id:`CTRL-${String(i+1).padStart(3,'0')}`,name:["Access control","MFA","Logging","Incident response","Change management","Vendor risk","Encryption at rest","Encryption in transit","Backup and recovery","Vulnerability management"][i%10]+` ${i+1}`,framework:frameworks[i%5],domain:['Identity','Operations','Risk','Data Protection','Governance'][i%5],status:(['Implemented','Partially Implemented','Not Implemented','Not Applicable'] as Status[])[i%4],maturity:(i%5)+1,owner:['Security TPM','GRC Lead','Engineering Manager','IT Manager','Compliance Manager'][i%5]}));
export const evidence = Array.from({length:24}).map((_,i)=>({id:`EVD-${i+1}`,controlId:controls[i].id,framework:controls[i].framework,name:['MFA policy screenshot','Access review export','Incident response plan','Change ticket sample','Vulnerability scan summary'][i%5],status:['Missing','Submitted','Expired','Approved','Needs Review'][i%5],expiresInDays:[-3,10,45,120,5][i%5]}));
export const risks = Array.from({length:18}).map((_,i)=>{const likelihood=(i%5)+1; const impact=((i+2)%5)+1; const score=likelihood*impact; const sev= score>=20?'Critical':score>=12?'High':score>=6?'Medium':'Low'; return {id:`RSK-${i+1}`,title:`Risk ${i+1}`,framework:frameworks[i%5],likelihood,impact,score,severity:sev,dueDays:[-20,-5,4,30,60][i%5],owner:['Security TPM','GRC Lead','Infra Lead'][i%3]};});
export const remediations=Array.from({length:22}).map((_,i)=>({id:`REM-${i+1}`,title:`Remediation ${i+1}`,status:['Not Started','In Progress','Blocked','Complete','Accepted Risk'][i%5],dueDays:[-14,-2,3,14,45][i%5],owner:['Engineering Manager','IT Manager','Product Security Lead','Compliance Manager'][i%4],priority:['Critical','High','Medium'][i%3]}));
export const milestones=[{name:'SOC 2 readiness review',date:'2026-06-15'},{name:'PCI gap assessment close',date:'2026-06-30'},{name:'HIPAA risk analysis sign-off',date:'2026-07-12'}];
export const readinessByFramework=frameworks.map((f,i)=>({framework:f,score:[78,66,59,74,71][i]}));
export const stats={overall:72,auditReadiness:69,evidenceHealth:68};
